### PR TITLE
Patches/record ordering

### PR DESCRIPTION
**Pull request by jtwiest**

### CODE REVIEW

**Comment by themightychris** [comment]
@jtwiest thanks for this PR! In other places where `'order'` configuration gets turned into SQL, something like this is done:

```php
if ($options['order']) {
    $query .= ' ORDER BY '.join(',', static::_mapFieldOrder($options['order']));
}
```

This provides for applying field mapping and SQL generation when the `['Key' => 'ASC', 'OtherKey' => 'DESC', 'MAX(One, Two) DESC']` order config syntax is used

**Comment by jtwiest** [comment]
@themightychris I'm using this in the relationship declaration specifically to do to this:

```
       'Transactions' => [
            'type' => 'many-many',
            'class' => Transaction::class,
            'linkClass' => StatementTransaction::class,
            'linkLocal' => 'StatementID',
            'linkForeign' => 'TransactionID',
            'order' => 'Related.Time ASC'
        ],
```

Is this good to get pulled in though? I'm overriding that function in a few places already.

**Comment by themightychris** [comment]
@jtwiest that's fine, the _mapFieldOrder function knows to pass a full string through as-is if that's what you give it, but anywhere in ActiveRecord that supports an 'order' option should still be getting run through that function. Please add before we merge

**Comment by jtwiest** [comment]
@themightychris think I addressed your concern, this is now ready for review again.

**Pull request merged**
