### PR TITLE
Added ability to compile pages within subdirectories

### PR DESCRIPTION
**Pull request by aharley40**
@themightychris Updated pages build code. Sorry this took so long to push.

### CODE REVIEW

**Comment by aharley40** [comment]
@themightychris Please review and merge these commits

**Comment by themightychris** [comment]
@aharley40 there unrelated changes to the Tag models in this PR

**Comment by themightychris** [comment]
Also sites with skeleton-v2 as an ancestor get their sencha build wrappers from this repo now, open a PR there too: https://github.com/JarvusInnovations/emergence-sencha

**Comment by themightychris** [comment]
@aharley40 I'd like to merge this but it needs to be cleaned up first

**Pull request closed without merging**
